import GlobalStyles from "@/providers/GlobalStyle";
import StyledComponentsRegistry from "@/providers/styledRegistry";
import { Roboto_Mono } from "next/font/google";
const roboto = Roboto_Mono({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
